import { StyleSheet } from "react-native";

export const timerStyles = StyleSheet.create({
	textInput: {
		color: "#D9D9D9",
		textAlign: "right",
		paddingHorizontal: 8,
		fontSize: 18,
	},
	inputMetric: {
		color: "#393939",
		fontSize: 18,
		paddingHorizontal: 6,
		fontWeight: "600",
	},
	numInput: {
		marginHorizontal: 8,
		flexDirection: "row",
		justifyContent: "flex-end",
		alignItems: "center",
		borderColor: "#4E4E4E",
		borderStyle: "solid",
		borderWidth: 1,
		borderRadius: 8,
		width: 84,
		height: 40,
		overflow: "hidden",
	},
	counter: {
		fontSize: 64,
		fontWeight: "600",
		color: "#FFF",
	},
	msCounter: {
		fontSize: 32,
		fontWeight: "600",
		color: "#4e4e4e",
	},
	counterView: {
		width: "100%",
		borderStyle: "solid",
		borderBottomLeftRadius: 18,
		borderBottomRightRadius: 18,
		borderBottomWidth: 2,
		borderBottomColor: "#fff",
		justifyContent: "center",
		alignItems: "center",
		marginVertical: 24,
	},
	toggleTimerButton: {
		marginVertical: 24,
		height: 96,
		width: 96,
		alignSelf: "center",
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "#D9D9D9",
		borderRadius: 64,
	},
});
